# Ruby安定版
FROM ruby:3.3.6

# 言語設定
ENV LANG C.UTF-8

# タイムゾーン
ENV TZ Asia/Tokyo

# パッケージリストを出力抑えつつ最新に更新
RUN apt-get update -qq \
# HTTPS通信証明書ハッピーセット
&& apt-get install -y ca-certificates curl gnupg \
&& mkdir -p /etc/apt/keyrings \
&& curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg \
# Node.jsのリポジトリを追加
&& NODE_MAJOR=20 \
&& echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list \
# Yarnのリポジトリを追加
&& wget --quiet -O - /tmp/pubkey.gpg https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
&& echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list

# 追加のパッケージをインストール: C/C++ を含むコンパイル作業, PostgreSQL, Node.jsの実行環境, JavaScript パッケージマネージャー, テキストエディタVim
RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs yarn vim chromium

# Dockerコンテナ内のSleepLoggerディレクトリで作業
RUN mkdir /SleepLogger
WORKDIR /SleepLogger

# RubyのGem管理ツールBundlerをインストール
RUN gem install bundler

# ローカルディレクトリの内容をコンテナにコピー
COPY . /SleepLogger
